// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports
import "@mantine/core/styles.css";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";

import type { Metadata } from "next";
import { Inter, Merriweather, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const merriweather = Merriweather({
    weight: ["300", "400", "700", "900"],
    subsets: ["latin"],
});
const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <head>
                <ColorSchemeScript />
            </head>
            <body
                className={
                    openSans.className +
                    `
                        bg-neutral-100 text-neutral-800
                        antialiased max-w-2xl mb-40 flex flex-col md:flex-row mt-8 
                        lg:ml-72 px-4
                    `
                }
            >
                <MantineProvider>
                    <Navbar />
                    {children}
                </MantineProvider>
            </body>
        </html>
    );
}
